[package]
name = "factorial-debug"
version = "0.2.0"
authors = ["andrei-marinica <andrei_m_marinica@yahoo.com>"]
edition = "2018"

[dependencies]
elrond-wasm = "0.4.2"
elrond-wasm-debug = "0.4.2"

factorial = { path = ".." }
