[workspace]
members = [
  "adder",
  "adder/debug",
  "crypto-bubbles",
  "crypto-bubbles/debug",
  "factorial",
  "factorial/debug",
  "features",
  "features/debug",
  "simple-coin",
  "simple-coin/debug",
]