[package]
name = "factorial"
version = "0.1.3"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "factorial"
path = "src/lib.rs"


[dependencies]
elrond-wasm = "0.4.2"
elrond-wasm-node = "0.4.2"
elrond-wasm-derive = "0.4.2"
